name: Documentation

on:
  push:
    branches:
      - master
      - develop
    tags:
      - 'v*'
    paths:
      - 'docs/**'
      - 'mkdocs.yml'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install mkdocs
        run: pip install mkdocs-material

      - name: Build Documentation
        run: mkdocs build

      - name: Upload Documentation
        if: success()
        uses: actions/upload-pages-artifact@v2
        with:
          name: github-pages
          path: 'site/'

  pages:
    runs-on: ubuntu-latest
    needs: build
    if: success()

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy Documentation
        id: deployment
        uses: actions/deploy-pages@v2

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
